// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AvatorsColumns holds the columns for the "avators" table.
	AvatorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "bio", Type: field.TypeString},
		{Name: "user_avators", Type: field.TypeInt, Nullable: true},
	}
	// AvatorsTable holds the schema information for the "avators" table.
	AvatorsTable = &schema.Table{
		Name:       "avators",
		Columns:    AvatorsColumns,
		PrimaryKey: []*schema.Column{AvatorsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "avators_users_avators",
				Columns:    []*schema.Column{AvatorsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AvatorsTable,
		UsersTable,
	}
)

func init() {
	AvatorsTable.ForeignKeys[0].RefTable = UsersTable
}
