// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yDog-1/woodon_server/ent/avator"
	"github.com/yDog-1/woodon_server/ent/predicate"
	"github.com/yDog-1/woodon_server/ent/user"
)

// AvatorUpdate is the builder for updating Avator entities.
type AvatorUpdate struct {
	config
	hooks    []Hook
	mutation *AvatorMutation
}

// Where appends a list predicates to the AvatorUpdate builder.
func (au *AvatorUpdate) Where(ps ...predicate.Avator) *AvatorUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetName sets the "name" field.
func (au *AvatorUpdate) SetName(s string) *AvatorUpdate {
	au.mutation.SetName(s)
	return au
}

// SetNillableName sets the "name" field if the given value is not nil.
func (au *AvatorUpdate) SetNillableName(s *string) *AvatorUpdate {
	if s != nil {
		au.SetName(*s)
	}
	return au
}

// SetBio sets the "bio" field.
func (au *AvatorUpdate) SetBio(s string) *AvatorUpdate {
	au.mutation.SetBio(s)
	return au
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (au *AvatorUpdate) SetNillableBio(s *string) *AvatorUpdate {
	if s != nil {
		au.SetBio(*s)
	}
	return au
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (au *AvatorUpdate) SetOwnerID(id int) *AvatorUpdate {
	au.mutation.SetOwnerID(id)
	return au
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (au *AvatorUpdate) SetNillableOwnerID(id *int) *AvatorUpdate {
	if id != nil {
		au = au.SetOwnerID(*id)
	}
	return au
}

// SetOwner sets the "owner" edge to the User entity.
func (au *AvatorUpdate) SetOwner(u *User) *AvatorUpdate {
	return au.SetOwnerID(u.ID)
}

// Mutation returns the AvatorMutation object of the builder.
func (au *AvatorUpdate) Mutation() *AvatorMutation {
	return au.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (au *AvatorUpdate) ClearOwner() *AvatorUpdate {
	au.mutation.ClearOwner()
	return au
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AvatorUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AvatorUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AvatorUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AvatorUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AvatorUpdate) check() error {
	if v, ok := au.mutation.Name(); ok {
		if err := avator.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Avator.name": %w`, err)}
		}
	}
	return nil
}

func (au *AvatorUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(avator.Table, avator.Columns, sqlgraph.NewFieldSpec(avator.FieldID, field.TypeInt))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(avator.FieldName, field.TypeString, value)
	}
	if value, ok := au.mutation.Bio(); ok {
		_spec.SetField(avator.FieldBio, field.TypeString, value)
	}
	if au.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   avator.OwnerTable,
			Columns: []string{avator.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   avator.OwnerTable,
			Columns: []string{avator.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{avator.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AvatorUpdateOne is the builder for updating a single Avator entity.
type AvatorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AvatorMutation
}

// SetName sets the "name" field.
func (auo *AvatorUpdateOne) SetName(s string) *AvatorUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (auo *AvatorUpdateOne) SetNillableName(s *string) *AvatorUpdateOne {
	if s != nil {
		auo.SetName(*s)
	}
	return auo
}

// SetBio sets the "bio" field.
func (auo *AvatorUpdateOne) SetBio(s string) *AvatorUpdateOne {
	auo.mutation.SetBio(s)
	return auo
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (auo *AvatorUpdateOne) SetNillableBio(s *string) *AvatorUpdateOne {
	if s != nil {
		auo.SetBio(*s)
	}
	return auo
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (auo *AvatorUpdateOne) SetOwnerID(id int) *AvatorUpdateOne {
	auo.mutation.SetOwnerID(id)
	return auo
}

// SetNillableOwnerID sets the "owner" edge to the User entity by ID if the given value is not nil.
func (auo *AvatorUpdateOne) SetNillableOwnerID(id *int) *AvatorUpdateOne {
	if id != nil {
		auo = auo.SetOwnerID(*id)
	}
	return auo
}

// SetOwner sets the "owner" edge to the User entity.
func (auo *AvatorUpdateOne) SetOwner(u *User) *AvatorUpdateOne {
	return auo.SetOwnerID(u.ID)
}

// Mutation returns the AvatorMutation object of the builder.
func (auo *AvatorUpdateOne) Mutation() *AvatorMutation {
	return auo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (auo *AvatorUpdateOne) ClearOwner() *AvatorUpdateOne {
	auo.mutation.ClearOwner()
	return auo
}

// Where appends a list predicates to the AvatorUpdate builder.
func (auo *AvatorUpdateOne) Where(ps ...predicate.Avator) *AvatorUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AvatorUpdateOne) Select(field string, fields ...string) *AvatorUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Avator entity.
func (auo *AvatorUpdateOne) Save(ctx context.Context) (*Avator, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AvatorUpdateOne) SaveX(ctx context.Context) *Avator {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AvatorUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AvatorUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AvatorUpdateOne) check() error {
	if v, ok := auo.mutation.Name(); ok {
		if err := avator.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Avator.name": %w`, err)}
		}
	}
	return nil
}

func (auo *AvatorUpdateOne) sqlSave(ctx context.Context) (_node *Avator, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(avator.Table, avator.Columns, sqlgraph.NewFieldSpec(avator.FieldID, field.TypeInt))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Avator.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, avator.FieldID)
		for _, f := range fields {
			if !avator.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != avator.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(avator.FieldName, field.TypeString, value)
	}
	if value, ok := auo.mutation.Bio(); ok {
		_spec.SetField(avator.FieldBio, field.TypeString, value)
	}
	if auo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   avator.OwnerTable,
			Columns: []string{avator.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   avator.OwnerTable,
			Columns: []string{avator.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Avator{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{avator.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
