// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Avator is the predicate function for avator builders.
type Avator func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
